---
include:
  - template: 'Jobs/Code-Intelligence.gitlab-ci.yml'
  - template: 'Security/Dependency-Scanning.gitlab-ci.yml'
  - template: 'Security/License-Scanning.gitlab-ci.yml'
  - template: 'Security/SAST.gitlab-ci.yml'
  - template: 'Security/Secret-Detection.gitlab-ci.yml'
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

variables:
  PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'

test:
  stage: test
  image: python:3-alpine
  cache:
    paths:
      - .cache
  artifacts:
    reports:
      cobertura: python-coverage.xml
      junit: pytest.xml
  coverage: '/^TOTAL .* (\d+%)$/'
  script:
    - source .gitlab/ci.sh
    - ci_section setup ./bin/setup
    - ci_section lint  ./bin/lint
    - ci_section test  ./bin/test
